
backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        editor:
          preview: false

# Menu navigation section (can be adjusted depending on actual usage)
menu:
  - name: Home
    label: Home
    url: /

  - name: Products
    label: Products
    url: /products

  - name: 产品介绍
    label: 产品介绍
    url: /products-cn
